### PR TITLE
Update ResourceInfo name datatype

### PR DESCRIPTION
**Pull request by swatisehgal**
- update from v1.ResourceName to string

Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

### CODE REVIEW

**Comment by swatisehgal** [comment]
@AlexeyPerevalov I added the vendor directory so that its straightforward to regenerate the code. Please let me know if you think it is okay to do so.

**Comment by AlexeyPerevalov** [comment]
I think we can add check for vendor directory and go mod vendor into hack/update-codegen.sh, instead of keeping it in git.

**Comment by swatisehgal** [comment]
Sure, updating the PR, will remove the vendor directory

**Comment by swatisehgal** [comment]
@AlexeyPerevalov Can we merge this now?

**Review by AlexeyPerevalov — APPROVED** [review]

**Pull request merged**
