### PR TITLE
crd: regenerate with v1alpha2

### PR DESCRIPTION
**Pull request by ffromani**
Followup to #25 regenerate the CRD including v1alpha2.

We will evaluate if we want to also offer version-specific CRDs alongside the all-in-one `manifests/crd.yaml`.

### CODE REVIEW

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by fmuyassarov** [comment]
Hi @ffromani 
I see that TopologyManager constants are still in API definitions (in v1alpha2), what's the plan of moving them out from NRT API?

**Comment by ffromani** [comment]
> Hi @ffromani I see that TopologyManager constants are still in API definitions (in v1alpha2), what's the plan of moving them out from NRT API?

The constants (and the `TopologyPolicies` field) are being deprecated starting `v1alpha2` and they will be removed as soon as we can break compatbility, so `v1beta1` (pending final review of the API graduation process standards)

**Comment by ffromani** [comment]
testbed for the new CRD version: https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/157

**Pull request merged**
